name: proyek_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  nb_utils: ^7.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: Poltawski Nowy
    fonts:
      - asset: assets/fonts/PoltawskiNowy-Regular.ttf
  - family: Plus Jakarta Sans Regular
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
  - family: Plus Jakarta Sans Bold
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Bold.ttf