name: proyek_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  nb_utils: ^7.0.4
  image_picker: ^1.1.2
  mime: ^1.0.6
  http_parser: ^4.0.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  whatsapp_unilink: ^2.1.0
  pdf: ^3.11.1
  share_plus: ^10.0.2
  path_provider: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: Poltawski Nowy
    fonts:
      - asset: assets/fonts/PoltawskiNowy-Regular.ttf
  - family: Plus Jakarta Sans Regular
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
  - family: Plus Jakarta Sans Bold
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Bold.ttf